### ISSUE TITLE
REST API: Copy REST_USERNAME button doesn't work.

### ISSUE THREAD

**Issue by kline7** [upstash/issues#101]
![image](https://github.com/upstash/issues/assets/28494838/31714179-88eb-4c28-b387-93aca0c2aab6)
In the Rest API section of the Kafka page, when a user clicks the 'Copy to clipboard' button, the value 'UPSTASH_KAFKA_REST_USERNAME' is copied instead of the actual username value.

**Comment by CahidArda** [comment]
Hi @kline7,

The problem should be sorted. We are closing this issue.
