### ISSUE TITLE
JSON string is pretty-printed in the data browser 

### ISSUE THREAD

**Issue by mmmulani** [upstash/issues#103]
When viewing a string that turns out to be JSON data (i.e. it was saved with `JSON.stringify`), the data browser pretty-prints it (i.e. displays it as though it was saved with `JSON.stringify(..., null, 2)`)

This was unexpected for me as I thought our backend was saving the data incorrectly. I was able to confirm from the CLI that we were saving the JSON in a minimal format. 

Overall I see the value in pretty printing the JSON here, but I wish I could toggle back to see exactly how it is being stored in Upstash.

**Comment by ytkimirti** [comment]
You are right, a pretty print switch would be better. I created a ticket for this, thanks for the feedback

**Comment by mmmulani** [comment]
oh after using the API more, it might be helpful to label it as `automaticDeserialization`? so that it corresponds to the JS API

**Comment by ytkimirti** [comment]
We changed how strings are shown in the databrowser, there is now a prettify button instead. Thank you for your suggestion

![image](https://github.com/upstash/issues/assets/18082091/93064979-0709-4d53-b9da-aa58d3407701)
![image (1)](https://github.com/upstash/issues/assets/18082091/f044b0bd-754f-4d17-9bc0-c28d1160247c)
