### ISSUE TITLE
Getting `SignatureError: "nbf" claim timestamp check failed` when calling `verifySignatureAppRouter` in Next.js

### ISSUE THREAD

**Issue by glennslaven** [upstash/issues#110]
I seem to intermittently get this error when receiving messages from the URL group. Often it will error twice then on the 3rd attempt it will work (we default to 3 retries).

I have ensured my clock is correct via `ntpdate pool.ntp.org`. I am running under Ubuntu 20.04.6 LTS in WLS2.

It looks like your `nbf` & `iat` values are identical in the JWT signature. It would be nice if there was a bit more tolerance for clock skew in there, even a minute or so earlier on the `nbf` would probably avoid these issues.

**Comment by CahidArda** [comment]
Hi @glennslaven,

If you want the tolerance to be a minute, you can try setting `clockTolerance` value to 60 seconds in the `verifySignatureAppRouter` config:

```ts
export const POST = verifySignatureAppRouter(
  (request: NextRequest) => {...},
  {
    clockTolerance: 60
  }
)
```

You can read more about clockTolerance [here](https://github.com/upstash/qstash-js/blob/main/platforms/nextjs.ts#L23).

**Comment by glennslaven** [comment]
That's awesome, thankyou
