### ISSUE TITLE
Sending batches of messages to a URL group and then changing the URL group urls doesn't update the pending messages

### ISSUE THREAD

**Issue by CarlosViller** [upstash/issues#115]
### Background

We were using the QStash JS SDK to send batches of messages to a URL group with a 1-minute delay per message. In the middle of the process, we encountered an error in our pipeline and wanted to cancel all the pending messages we had sent. We changed the URL group URIs to point to a dead link, but the messages continued arriving at our previous URLs.

**Question**  
Is this a bug or expected behavior? Should updating the URL group change the destination of pending messages?

If this is expected, how can we stop delayed messages from reaching their destination if we found an error in our pipeline?

**Comment by sancar** [comment]
Hi @CarlosViller , 
This is expected. 
You can cancel messages via rest API or sdks if you have the messageId's recorded. 
ts sdk:
https://upstash.com/docs/qstash/sdks/ts/examples/messages#cancel-delete-a-message

Rest API
https://upstash.com/docs/qstash/api/messages/cancel
https://upstash.com/docs/qstash/api/messages/bulk-cancel


You can also use our console `Events` tab to find  and cancel messages. You can filter them by URL group to find them quicker and cancel them from there as well. 

<img width="1011" alt="Screenshot 2024-09-24 at 10 18 20" src="https://github.com/user-attachments/assets/1afa339c-f17d-4491-9f20-25b07af6cb1b">
