### ISSUE TITLE
Github account and gmail account has same db

### ISSUE THREAD

**Issue by heisaduvan** [upstash/issues#19]
In my personal laptop, I created an account using by github authentication then I created a redis db. One day later, I tried to login using by github authentication with my company laptop. But I could not login with github auth. Then, I signed up with gmail and password, I got the verification email and I succeed to login with gmail and password. But I saw the database that I already have in my github account was there as well. 

I could not understand the problem. I am not sure this is a bug or not.

**Comment by mdogan** [comment]
@heisaduvan; is your Github account email the same with Gmail? If yes, this is expected, since we register users with their emails, regardless of their authentication method.

**Comment by heisaduvan** [comment]
Yes, they were same. Actually this gmail address is one of my emails in github. Thank you so much for your interest, have a nice day.
