### ISSUE TITLE
Redis - error: "WRONGTYPE Operation against a key holding the wrong kind of value"

### ISSUE THREAD

**Issue by serkanserterSE** [upstash/issues#24]
Hi.
When I run the following code, I get an error, the data is in JSON type on Redis.

```
fetch("https://eu2-steady-wallaby-30045.upstash.io/get/W1", {
        headers: {
            Authorization: "Bearer *****"
        }
    }).then(response => response.json())
        .then(data => console.log(data));
```
![ss](https://user-images.githubusercontent.com/64686185/165471623-bf78dd08-9939-42b5-869c-ef944e8491ea.jpg)

**Comment by mdogan** [comment]
Hi @serkanserterSE, `get` command can only be used for `string` entries. What's the type of your key: `W1`? You can query its type using `https://eu2-steady-wallaby-30045.upstash.io/type/W1`.

**Comment by serkanserterSE** [comment]
Thanks for your help. The type of key is "hash"

**Comment by mdogan** [comment]
`get` command doesn't support `hash` keys. See hash commands: https://redis.io/commands/?group=hash
