### ISSUE TITLE
`srandmember` Always returns the same result ....

### ISSUE THREAD

**Issue by zkeq** [upstash/issues#25]
I try to use `srandmember` to get an item in a set.

#### Why does the srandmember command always return the same value when I use it?

![444](https://user-images.githubusercontent.com/62864752/166665688-a6fe37b5-fa4c-4423-8277-6678dfd40796.png)

#### Below is my code

![carbon](https://user-images.githubusercontent.com/62864752/166665407-51b9f924-920a-44af-b1f7-2e8c6f82b726.png)

#### Same code, two different results

![KX8MC{L%1GB~ WKL4D%B69F](https://user-images.githubusercontent.com/62864752/166669181-9a6ae16c-6d56-4a8c-8e47-1479bf83df03.png)

This is my database address, can you check it out for me?
```
Region
ap-northeast-1

Endpoint
apn1-destined-giraffe-32369.upstash.io
```

**Comment by zkeq** [comment]
I created a new collection, but the problem persists.

**Comment by zkeq** [comment]
Here is my data structure

![777](https://user-images.githubusercontent.com/62864752/166666939-bf734016-52b5-411f-a4d7-82694448a358.png)

**Comment by zkeq** [comment]
Redis command is also..

### local
![11](https://user-images.githubusercontent.com/62864752/166669933-00ee6408-c5e5-495c-8d8c-d69d7f6023f1.png)
![101010](https://user-images.githubusercontent.com/62864752/166669760-01fecd29-fb46-4d04-9fcf-0d032dfcdce7.png)

### upstash
![12](https://user-images.githubusercontent.com/62864752/166669948-12a8a28c-f95c-4e5d-8464-9480e718b08c.png)

![999](https://user-images.githubusercontent.com/62864752/166669768-563e256a-12b8-4f38-bff1-3d94d8184e53.png)

**Comment by mdogan** [comment]
Thanks for the report. This is an accidental issue caused by a latest change. As a workaround you can use `SRANDMEMBER` with `count=-1` option for the time being. The fix will be deployed soon.

**Comment by zkeq** [comment]
> Thanks for the report. This is an accidental issue caused by a latest change. As a workaround you can use `SRANDMEMBER` with `count=-1` option for the time being. The fix will be deployed soon.

> SRANDMEMBER bing_images -1

ok, i'm using it yet ..

**Comment by geoffrich** [comment]
I'm still seeing this issue. Is there an ETA on a fix?

**Comment by zkeq** [comment]
Looks like this issue is still not fixed

**Comment by mdogan** [comment]
The fix was deployed to all regions in July. You can report here if you still observe the issue. Thanks.
