### ISSUE TITLE
Data Browser Pagination Not Displaying The Remaining Records

### ISSUE THREAD

**Issue by mkaman** [upstash/issues#26]
When there are more than 10 records, the first 10 records are displayed on the first page however the next page is not containing the rest of the records.

1)
![1_v2](https://user-images.githubusercontent.com/3066562/168426437-71902fdb-acdb-46f2-8833-90e2bd2f4621.png)

2)
![2_upstash](https://user-images.githubusercontent.com/3066562/168426438-751c1843-ea28-45c8-83fc-b0cd8aa017c9.png)

**Comment by enesakar** [comment]
fixed
