### ISSUE TITLE
what is the max size of value in a single entry

### ISSUE THREAD

**Issue by brucemcpherson** [upstash/issues#3]
I'm using the GraphQL redisSet mutation, and it works well with smaller payloads, but I get an error 400 with bigger payloads. What is the maximum size of value that can be stored (and posted via a graphQL mutation)

**Comment by noahfschr** [comment]
The limit is 1Mb. What was your object's size?

**Comment by brucemcpherson** [comment]
About 3mb. Thanks .. I’ll split it up.

**Comment by noahfschr** [comment]
@brucemcpherson Thank you, I will check it.

**Comment by noahfschr** [comment]
Very nice article by the way @brucemcpherson 👌

**Comment by noahfschr** [comment]
@brucemcpherson Sorry, I thought your database type is standard which has 1Mb limit. For free databases the limit is 400Kb. 

I think we need to return a more descriptive error. I will create an issue regarding this.

**Comment by brucemcpherson** [comment]
Ok - makes sense now. Thank you.

**Comment by noahfschr** [comment]
created #4, closing this

**Comment by brucemcpherson** [comment]
@noahfschr I notice that redisMSet seems to fail too if the total of each payload is large, even though the individual values are all less then 400k. I'd assumed that the limit of 400k applied to each key/value pair - but it looks like it applies to the entire payload. Is that right, and would an MSet on the paid plan also have the 1mb limit on the sum of the keyvaluepairs rather than each individual value?

**Comment by noahfschr** [comment]
@brucemcpherson Let me explain the background of this limit. The cloud provider (AWS) charges us for the data transferred. Our pricing is per request. If we do not put limit on the request size, then it can be a financial risk as the data transfer cost can be very high.

The limit is per request size. The MSET command is serialized as a single request. Its total size should be less than the limit which is 400Kb for Free databases. So if you split your payload to multiple values, you need to send with seperate commands (multiple SET commands).

**Comment by brucemcpherson** [comment]
Yep - got it. Makes perfect sense. Thanks for the background info.
