### ISSUE TITLE
Console/redis-page shows outdated node-redis createClient syntax

### ISSUE THREAD

**Issue by jenssogaard** [upstash/issues#32]
Page: `https://console.upstash.com/redis/{xxxxxxx}` shows outdated example code for node-redis.

In the "Connect to your database"-section:
```
var client = redis.createClient ({
  host : '****.upstash.io',
  port : '*******',
  password: '********'
});
```

node-redis v4+ do not use `host` property and instead expecs `url` - see documentation: https://github.com/redis/node-redis#usage

**Comment by ademilter** [comment]
thank you @jenssogaard fixed 🚀
