### ISSUE TITLE
Large numbers are returned in scientific notation

### ISSUE THREAD

**Issue by malte-j** [upstash/issues#34]
I'm using a sorted set and use ZRANGE to retrieve its entries. On the screenshot on the left is the current redis release on my machine, and on the right the response from upstash redis, hosted on fly.io. As you can see upstash returns numbers in scientific notation. In Nodejs "ioredis" interprets them as just 1. Is there any way to turn this off?

![image](https://user-images.githubusercontent.com/12611076/200340436-050b412e-bb08-4fab-8cdd-73eb9acf1efa.png)

**Comment by SkyGuardian42** [comment]
I tried both `Date.now()` which is as a length of 13 and `Math.floor(Date.now() / 1000)` with a length of 10. Here's the full snippet:
```typescript
redis.zadd(
  "key",
  Math.floor(Date.now() / 1000),
  fileId
);
```

I thought the problem could be ioredis, but it still happens using just redis-cli:

![image](https://user-images.githubusercontent.com/12611076/200388257-e0bc6bc9-09c3-43fc-a275-3fc7fb8022ad.png)

**Comment by chronark** [comment]
As I said above, the official redis will also use scientific notation at some point.
Ioredis returns the number as string to you, so it's up to you to parse it, which works as expected when using `parseFloat`.

Please share the code you tried, so I can help debug it.

**Comment by SkyGuardian42** [comment]
Thank you, it works using parseFloat for now. I'm more worried what happens if the timestamp exceeds the float precision. Is there any documentation on what the maximum value on Upstash is, or is there any way to raise the precision for my instance?

**Comment by chronark** [comment]
This will break beyond javascripts `MAX_SAFE_INTEGER`, which is `9007199254740991`
but that's unrelated to upstash and is a limitation of javascript. However that still gives you a few hundred years.

And you are not losing any precision
A value from your example above:
`1.667652292239e+12` is as precise as `1667652292239`
it's a different representation.

**Comment by chronark** [comment]
We've changed it on our end and now use the same representation as the official redis.
