### ISSUE TITLE
HGETALL not working with Deno Redis client

### ISSUE THREAD

**Issue by hwclass** [upstash/issues#37]
While sending a command to an Upstash Redis store via [Deno Redis client](https://deno.land/x/redis@v0.27.4/protocol/mod.ts?s=sendCommand), as it was working successfully with a `hset` method like the following:

```ts
await redis.sendCommand("HSET", <HASH>, <KEY>, <VALUE>)
```  

it does not seem working with HGETALL & just returning `{"code":42}`.

```ts
const reply = await redis.sendCommand("HGETALL", <HASH>)
```

As I was not sure if that's because of the library's internal problem or not, just wanted to make sure if that's an issue from Upstash side.

Thanks in advance.

**Comment by chronark** [comment]
@hwclass 
```ts
const hgetall = await redis.hgetall("hash")
```
this works, please use that for now, while I try to figure out what's going on

not sure why the `sendCommand` returns this


Also if you want an edge friendly redis client, that works over HTTP, you can consider using https://deno.land/x/upstash_redis@v1.18.1

**Comment by hwclass** [comment]
@chronark Thanks for the tip & the additional info! will try it out...

**Comment by chronark** [comment]
For anyone else encountering this:
You need to call `.value()` on the response

```ts
redis.sendCommand("HGETALL","hash")
console.log(hgetall.value())
```
