### ISSUE TITLE
Redis ltrimmed data is spontaneously restored

### ISSUE THREAD

**Issue by spbriggs** [upstash/issues#38]
I'm having a strange situation where, after an LTRIM operation, the list is correctly shown as having been trimmed but after 5-10 minutes the trimmed data reappears. I'm using a Cloudflare Worker with the upstash/redis/cloudflare SDK but I've also reproduced the behaviour in the CLI.

See screenshot below

![Screenshot 2022-12-24 at 19 53 41](https://user-images.githubusercontent.com/723001/209440015-143ba513-43bb-4b38-a6f6-36e2cc6da09a.png)

**Comment by mdogan** [comment]
Hi @spbriggs, are you able to reproduce this consistently? I'm assuming there is no write to this list in the mean time. 

Also which region is your database in?

**Comment by spbriggs** [comment]
Hi @mdogan 

I've tested it both with and without an intervening write to the list and in both cases the trimmed records reappeared. That said, I've not done a comprehensive test case so it's possibly just limited to this one list for some reason. I might get some time over Christmas to test more extensively. 

My DB is in eu-west-1

**Comment by mdogan** [comment]
Thanks for the report @spbriggs. We are able to reproduce this issue. A fix will be deployed this week hopefully. I'll inform you over this ticket when it's deployed to eu-west-1 region.

**Comment by spbriggs** [comment]
Thanks for such prompt attention @mdogan. I'm glad you were able to reproduce it as I thought I was going mad or doing something wrong myself :)

**Comment by spbriggs** [comment]
Hi @mdogan, have you had a chance to deploy this fix yet?

**Comment by mdogan** [comment]
sorry for the delay @spbriggs. I've just asked ops team about the deployment. waiting for their response...

**Comment by mdogan** [comment]
Hi @spbriggs, the fix is deployed to eu-west region. You can verify database version using `INFO SERVER` command. You should see `upstash_version:1.5.1` there.

**Comment by spbriggs** [comment]
Thanks @mdogan . I've confirmed that the upstash_version is 1.5.1 and that the fix is successful. Thanks for your help in resolving this issue.
