### ISSUE TITLE
Missing support for callback in REST API

### ISSUE THREAD

**Issue by step135** [upstash/issues#44]
Also the second issue is that adding callback to the query is considered that "callback" should be a name of  key in db.

**Comment by chronark** [comment]
Are you referring to QStash?
I'm confused since you mentioned a database?


Can you explain more please?

**Comment by step135** [comment]
Redis

**Comment by step135** [comment]
Redis

**Comment by chronark** [comment]
Do you mean [keyspace notifications](https://redis.io/docs/manual/keyspace-notifications/)?


Please explain more.

**Comment by step135** [comment]
REST API, just read the title!!!

**Comment by step135** [comment]
You don't know what REST API is? Shame on you!!!

**Comment by chronark** [comment]
I'll close this

I don't understand what callbacks you mean when talking about the rest api.
Feel free to reopen it and add a description.
