### ISSUE TITLE
Validation of global redis database applied when creating regional database 

### ISSUE THREAD

**Issue by alexander-schreiner** [upstash/issues#45]
When creating a new redis database when on the free tier, follow the following steps:

1. Click "Create database"
2. Select type "Global"
3. Choose two read regions
4. Switch back to type "Regional"
5. Enter a random name
6. Click "Create"

A validation error will pop up: "you can select at most one read region in free plan"

This shouldn't happen, as I am trying to create a regional database, not a global

**Comment by chronark** [comment]
Thanks, I'll forward it to the team

**Comment by chronark** [comment]
This is fixed and should be deployed or deployed very soon
thanks again for reporting it
