### ISSUE TITLE
Management API or Terraform for connectors

### ISSUE THREAD

**Issue by anthonyjgrove** [upstash/issues#51]
Curious if the connectors can be managed in terraform or via API? Couldn't find any information in the documents.

**Comment by sancar** [comment]
Unfortunately, we haven't prepared the Management API or Terraform yet. I will make sure that the relevant team has seen this request and update here as soon as we take an action.

**Comment by burak-upstash** [comment]
hello, @anthonyjgrove.
We have released the developer api, and terraform provider v1.4.0 which lets you configure your connectors in open format. Thanks for the issue!
