### ISSUE TITLE
[RateLimit] Nothing displayed on `Rate Limit Analytics` panel because the `identifier` is not a valid ip?

### ISSUE THREAD

**Issue by dreamer2q** [upstash/issues#52]
My Code as follows:

1. create a common function for reuse

```js
import { Ratelimit } from '@upstash/ratelimit';
import redis from '../redis';
import { getRealIp } from './ip';

/**
 * @param {string} key
 * @param {number} token
 * @param {string} duration
 * @returns
 */
export function createRateLimit(key, tokens, duration) {
  const limiter = new Ratelimit({
    redis,
    limiter: Ratelimit.fixedWindow(tokens, duration),
  });

  return {
    check: async (req, res) => {
      const reqIp = getRealIp(req);
      const reqIdentifier = `${reqIp}:${key}`; // please note here, its not a valid ip, it got a suffix~
      const { success, limit, remaining, reset } = await limiter.limit(
        reqIdentifier,
        req
      );
      res.setHeader('X-RateLimit-Limit', limit);
      res.setHeader('X-RateLimit-Remaining', remaining);
      res.setHeader('X-RateLimit-Reset', reset);
      return success;
    },
  };
}
```

2. use it in any api route I want to setup ratelimit
```js

const limit = createRateLimit('search', 50, '1h'); // please note the key

/**
 * @param {import('next').GetServerSidePropsContext} param0
 * @returns
 */
export async function getServerSideProps({ req, res, query }) {
  const passed = await limit.check(req, res);
  if (!passed) {
    return {
      redirect: {
        destination:
          '/error?msg=' + encodeURIComponent('RateLimit Error or anything you like here~'),
      },
    };
  }
 ......
}
```

after that, deployed, and worked, but nothing in `Rate Limit Analytics` panel.

I have checked the rawData, its working ~

It looks that the Panel not recoginized with what I set as an identifier~ Bad news.

**Comment by dreamer2q** [comment]
Sample Picture of Data View here, please take note of the `key` !!!

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/56211747/232730090-59d9b25d-b6f2-46f8-a3d4-19c120fa578e.png">

**Comment by chronark** [comment]
hey, you need to opt into analytics:
```ts
new Ratelimit({
    redis,
    limiter: Ratelimit.fixedWindow(tokens, duration),
    analytics: true // <-  
  });
  ```

**Comment by dreamer2q** [comment]
> hey, you need to opt into analytics:
> 
> ```ts
> new Ratelimit({
>     redis,
>     limiter: Ratelimit.fixedWindow(tokens, duration),
>     analytics: true // <-  
>   });
> ```

The `analytics` default is `true`,  am I wrong? 

<img width="830" alt="image" src="https://user-images.githubusercontent.com/56211747/232731016-5cca1550-bdc7-492b-ba27-b72d47577a32.png">

**Comment by chronark** [comment]
It was true on accident, we have set it to false in the latest version, since we don't want to add any cost to our users by default
what version are you on?

**Comment by dreamer2q** [comment]
I will set `analytics: true` and redeploy to see if working.



> It was true on accident, we have set it to false in the latest version, since we don't want to add any cost to our users by default what version are you on?

package.json says `"@upstash/ratelimit": "^0.4.2"` as well as yarn.lock

**Comment by dreamer2q** [comment]
Thanks for your attention. Its working now~ closed.

Docs should follow the latest code as it suggests or whatever

**Comment by chronark** [comment]
it adds 1 command per limit invocation

**Comment by dreamer2q** [comment]
> it adds 1 command per limit invocation

So the usage is doubled if analytics enabled?

**Comment by chronark** [comment]
that depends on the algorithm used.
you can check [here](https://github.com/upstash/ratelimit/blob/main/packages/sdk/src/single.ts) where all the algorithms are implemented
