### ISSUE TITLE
Direction Redis connection URL

### ISSUE THREAD

**Issue by donpark** [upstash/issues#56]
Redis connection URL displayed in Upstash redis console page at `https://console.upstash.com/redis/xxxx` looks like this:

```
redis://default:xxxxx@usw1-apt-jackal-xxxxxx.upstash.io:30852
```

But connection fails using `redis-cli` and `ioredis` unless URL scheme is changed from **`redis://`** to **`rediss://`**.

**Comment by chronark** [comment]
Can you show me a screenshot where that is displayed incorrectly?

**Comment by donpark** [comment]
Here you go.

<img width="1043" alt="screenshot_1299" src="https://github.com/upstash/issues/assets/127594/5fdc2613-6918-4f84-97d7-273268801ab5">

**Comment by chronark** [comment]
Oh indeed, that seems to have broken, we used to display it correctly. I'll fix it, thank you

**Comment by chronark** [comment]
did you copy the redis-cli command and try it?
tls is enabled by the `--tls` flag

and in the ioredis example (when you go to the `Node` tab), it is also displayed correctly

<img width="988" alt="CleanShot 2023-05-26 at 11 52 57@2x" src="https://github.com/upstash/issues/assets/18246773/43368ed2-a21f-4084-b53d-9ace24909bce">

**Comment by donpark** [comment]
Closing this issue because there is disagreement on whether how it's documented is misleading or not.

**Comment by chronark** [comment]
I'm not disagreeing
if you or anyone else got blocked by it, then it's something we need to address.
I was just asking because you brought up those two (redis-cli and ioredis) specifically
