### ISSUE TITLE
[Docs] QStash create message endpoint docs don't include Upstash-Deduplication-Id header

### ISSUE THREAD

**Issue by miketromba** [upstash/issues#62]
Is this intentional? The `Upstash-Deduplication-Id` header is not documented in the endpoint docs for [/v2/publish](https://upstash.com/docs/qstash/api/messages/create)

This, in combination with https://github.com/upstash/issues/issues/61, leads me to question whether the header is supported in `v2`... is it?

Edit: The `Upstash-Not-Before` header doesn't show on that page either... is it depreciated or something?

**Comment by sancar** [comment]
v2 docs are in progress and not ready. We hide them for now after feedback. 
`Upstash-Deduplication-Id` and `Upstash-Not-Before` is supported in v2 but v2 is not publicly announced yet.

**Comment by chronark** [comment]
Neither one is deprecated, I'll add them back
