### ISSUE TITLE
[Enhancement] QStash request builder demo still uses v1 endpoint

### ISSUE THREAD

**Issue by miketromba** [upstash/issues#63]
See CURL request in screenshot below. Seems like we're encouraged to use the `v1` endpoint based on this, but in the docs it says `v1` is depreciated.

Maybe you guys just shipped `v2` and are aware / intend to do all these things and in that case, apologies for spamming your issues tracker!

![image](https://github.com/upstash/issues/assets/25141252/07890733-de71-445f-bc1e-6efb2e37fc0e)

**Comment by sancar** [comment]
Hi @miketromba , v2 is not exactly live yet. We are preparing the console UI for v2. It will be ready soon. Please stick to v1 for now. 
We have reverted the docs not to mention v2 until console is ready as this is creating confusion. 
Thanks for the feedback.
