### ISSUE TITLE
[Docs] QStash rate limiting headers need documentation

### ISSUE THREAD

**Issue by miketromba** [upstash/issues#65]
In production I'm getting undocumented response headers like:

```http
Burst-Ratelimit-Limit: 150
Burst-Ratelimit-Remaining: 149
Burst-Ratelimit-Reset: 1692222677
```

In my case, I'm building an email marketing SaaS that has very bursty publishing patterns - thousands per second sometimes. In cases like these, it's important for engineers to know about these headers ahead of time while designing their systems.

**Comment by sancar** [comment]
Thanks for letting us know. It seems, they got last while we migrate the documentation to the new system. We will add them back.

**Comment by CahidArda** [comment]
Addressing this issue in https://github.com/upstash/docs/pull/271
