### ISSUE TITLE
[Bug] Discord invite link is broken on the Upstash website / in the console

### ISSUE THREAD

**Issue by miketromba** [upstash/issues#66]
The invite link is broken: https://discord.com/invite/w9SenAtbme

![image](https://github.com/upstash/issues/assets/25141252/4b8defd7-f604-4a9e-9445-ff9ff5612c93)

**Comment by chronark** [comment]
Hey @miketromba, can you click the "Why is my invite invalid" and let us know what it says
I just tried the link and it worked for me

**Comment by miketromba** [comment]
After re-authenticating on Discord's web app, the link is working
