### ISSUE TITLE
local testing of qstash

### ISSUE THREAD

**Issue by vincentserpoul** [upstash/issues#67]
Is there a way to locally develop with qstash through a container for example?

**Comment by vincentserpoul** [comment]
I created this, for the time being
https://github.com/vincentserpoul/qstash-simulator

**Comment by chronark** [comment]
Hey, we recommend using a tunnel like ngrok for the time being
https://upstash.com/docs/qstash/howto/local-tunnel

**Comment by vincentserpoul** [comment]
I was doing this at the beginning, but it was a bit more troublesome.
we only use the callback for now, so it's quite straightforward to simulate.
