### ISSUE TITLE
QStash: Unable to cancel scheduled jobs

### ISSUE THREAD

**Issue by jimkyndemeyer** [upstash/issues#69]
Hey,

Looks like the cancel action on scheduled QStash jobs doesn't work. See attached video.

https://github.com/upstash/issues/assets/15837712/4c3f320c-4b82-41ea-9908-eb7a96dbbd93

**Comment by chronark** [comment]
Hey @jimkyndemeyer we figured it out and will deploy a fix shortly

**Comment by chronark** [comment]
Should work now, can you confirm?
