### ISSUE TITLE
Console should default to last-selected team

### ISSUE THREAD

**Issue by wobedi** [upstash/issues#70]
## Steps to reproduce
Log in to Upstash web console

## Current behavior
"Personal" team loads

## Expected behavior
Last-selected team should load

## Impact
Would solve the minor inconvenience of having to switch team each time I log in

**Comment by CahidArda** [comment]
Hi @wobedi,

Console was updated with this feature. Closing this issue. Thanks for the suggestion!

**Comment by wobedi** [comment]
@CahidArda The console now even remembers my last selected database - nice! 
Thank you for that.

**Comment by wobedi** [comment]
@CahidArda FYI this seems to be broken again

**Comment by wobedi** [comment]
@CahidArda Now its fixed again :)
