### ISSUE TITLE
Can not see the messages in free trail

### ISSUE THREAD

**Issue by AamerHejazi** [upstash/issues#76]
Hello team,

As I was checking the tool I found that I could not see the messages after production messages.

The message counter is not increment and I should be in live mode to see the messages so the counter will increment.

Thank You

**Comment by sancar** [comment]
Hi @AamerHejazi , 

It should work irrelevant of the plan. It should work for the free plan as well. 

It does not fetch the old messages. You should first open the messages window, then produce. You should see the new produced messages only. 

I hope this helps. Let us know if issue persists

**Comment by AamerHejazi** [comment]
Dear @sancar 
Thank you for your response,

Also, I detected another issue once I produce a message without opening the messages window the message counter sometimes increases and sometimes not, But once I open the messages window all messages will reach and the counter of the messages will work normally.

Thank you,

**Comment by sancar** [comment]
There can be a gap between the counter and the actual publish/consume ops count.
We can investigate further if the counter does not match the actual usage but the delay is expected.
Closing the issue for now, let us know if anything else seems to be not working correctly.
