### ISSUE TITLE
Body without newlines does not show all of the data in read-only editor

### ISSUE THREAD

**Issue by Cliftonz** [upstash/issues#78]
![CleanShot 2023-11-02 at 06 27 00](https://github.com/upstash/issues/assets/43915749/15e511ec-12e4-496f-a83f-ca8c7b2026d0)

**Comment by buggyhunter** [comment]
Hello @Cliftonz can you give more context? Is the screenshot from Upstash Console?

**Comment by Cliftonz** [comment]
Yes, if the value has no /n character the full value of the message is not shown.

**Comment by Cliftonz** [comment]
@buggyhunter just following up

**Comment by ogzhanolguncu** [comment]
Hey @Cliftonz, this is fixed now. Feel free to check it out.
