### ISSUE TITLE
Migration page's link to old API documentation is broken

### ISSUE THREAD

**Issue by zachblume** [upstash/issues#82]
https://upstash.com/docs/qstash/migrating/v2

Links to v1 page

But how to navigate inside v1 documentation is unclear

e.g., if i click a link on the left menu, I then get the v2 documentation

I ended up manually editing the URLs to find old documentation

**Comment by fahreddinozcan** [comment]
Hi @zachblume,

the API documentation related to v1 still exists on the docs page, other than some changes in the API endpoints, most of the concepts in the v1 remains the same in v2(with some additions such as DLQ etc.). So we don't provide versioned docs for QStash v1. If you have any questions that you can't find the answer for in the docs (you can also use the chat bot in the top bar), you can ask us directly via mail or Discord. I should also mention that endpoints for v1 will soon be terminated, so we'd suggest working with v2.

Hope that helps
